inherit:
    - models/tiny.yaml

model:
    n_dims: 19  # 2*num_runs - 1 = 2*10 - 1 = 19
    n_positions: 101

training:
    task: ar_mixture
    data: ar_mixture
    task_kwargs:
        num_mixture_models: 3  # Size of coefficient pool
        num_runs: 10  # Number of runs per sample (9 context + 1 prediction)
        noise_std: 0.2
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 10001
    curriculum:
        dims:
            start: 19
            end: 19
            inc: 1
            interval: 2000
        points:
            start: 20  # Length of each run
            end: 20
            inc: 2
            interval: 2000
        lag:
            start: 3  # AR(3) process
            end: 3
            inc: 1
            interval: 1000

out_dir: ../models/ar_mixture_multirun

wandb:
    project: ar_mixture_multirun
    entity: null
    notes: "Multi-run AR mixture with progressive format - 10 runs, 3 models in pool"
    log_every_steps: 100

test_run: False
