inherit: 
    - models/tiny.yaml

model:
    n_dims: 3
    n_positions: 101

training:
    task: ar_warmup
    data: ar_warmup  # Use the new ARWarmupSampler
    task_kwargs: {"lag": 3}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 5001
    curriculum:
        dims:
            start: 1
            end: 1
            inc: 1
            interval: 2000
        points:
            start: 11
            end: 11
            inc: 2
            interval: 2000

out_dir: ../models/ar_warmup

wandb:
    project: ar_warmup
    entity: null
    notes: "warmup AR(q) experiment"
    log_every_steps: 100


test_run: False